version: '3.3'
services:
  api:
    build: 
      context: .
      dockerfile: src/server/Dockerfile
    ports:
      - 5001:5000
  web:
    build:
      context: .
      dockerfile: src/web_app/Dockerfile
    ports:
      - 8080:80
