name: Report Coverage

on:
  push:
    branches: [ "master", "CI" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest
    environment: codacy
    
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install coverage pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Create coverage report
      run: |
        coverage run -m pytest
        coverage lcov
        a=$(coverage report | grep "TOTAL")
        echo "Coverage:" ${a##T* }
        
    - name: Sending report
      run: |
        bash <(curl -Ls https://coverage.codacy.com/get.sh) report --project-token $CODACY_PROJECT_TOKEN -r coverage.lcov
      env:
        CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_PROJECT_TOKEN }}
